function features2 = getSsaenFeature(X)

hiddenSize = 10;
autoenc1 = trainAutoencoder(X,hiddenSize,... 
        'L2WeightRegularization',0.001,... 
        'SparsityRegularization',4,...... 
        'SparsityProportion',0.05,...... 
        'DecoderTransferFunction','purelin');

features1 = encode(autoenc1,X);

hiddenSize = 6;
autoenc2 = trainAutoencoder(features1,hiddenSize,...
        'L2WeightRegularization',0.001,...
        'SparsityRegularization',4,...
        'SparsityProportion',0.05,...
        'DecoderTransferFunction','purelin',...
        'ScaleData',false);

features2 = encode(autoenc2,features1);
features2 = features2';

end